language: go
sudo: false
go:
  - "1.11"
install:
  - "go mod download"
env:
  global:
    - NAME=clash
    - BINDIR=bin
    - GO111MODULE=on
script:
  - go test ./...
before_deploy: make -j releases
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    secure: secure: "J2ja9o4jgImrIqcFM/AC6H9eqEIQ93V5M4ZZguJlTgvMFzaisVn6AsIk61ruyKz9kobCiDSPQW4d6KYRU7r+fYK7sfKne05XvXBcRen+8LPn7bEf7Gs+XshC2EcEmPbYNhBqrVCyDWLIRr8VoaazKSFjD8zWFQcx7inPKSXgdIm9ssFYsfsFpfQzOaAHORLT9ZbDISi/+uwOD2MVejbUYYkqJIoXwSOHEr4J5E34EY0aJFEHHj711VKeu3UTTX4teAXg49Ik7iHqPGwaSn4LwUgwGRc4mWAkHHmaIz9VEiGuL6hYbT7sM6kvjlk0BL2iE6+IPvNybRqvb0g5+E75yqfgKaALyiNWFpK2h4b2w1YcM7rH00cbWh29yu2I+USB8/knB/8FfiAOl5gpZmiw0KRzXOWep6qMd92OlApyAMZ78Nv3QSJ4MQZSEtbqIdYy5iObIVcGvgI+HLQ3xk10o9wra+Btx57B82ga6EnpOTBhywNR91GMflGh+hdCvpSjhhf+fDCuxjqRDRx2Uo1fWGOHPo3rwW7XGnQEVACbv2aCX65zQj8OmKhrsYH6eaVpKq/Ln2rtd1FYgYMm4KXDlXYTJOEc4RoqQESwBDvwimeCcajNwYlZd+nVh8lygFFxtPD4+cBphZd6IuOJMrWrTqpiUli+/06TmkWPSO2eH9s="
  file: bin/*
  file_glob: true
  on:
    repo: silvernoo/clash
    branch: master
    tags: true
